version: 2.1
orbs:
  snyk: snyk/snyk@1.1.2

jobs:
  build:
    docker:
      - image: cimg/python:3.10.8
    steps:
      - checkout
      - run: pip install -r requirements.txt
  snyk_code_test:
    docker:
    - image: snyk/snyk-cli:npm
    steps:
    - checkout
    - run:
        command: | 
          snyk auth $SNYK_TOKEN
          snyk code test || true
  snyk_oss_test:
    docker:
    - image: snyk/snyk-cli:npm
    steps:
    - checkout
    - run:
        command: |
          snyk auth $SNYK_TOKEN
          snyk test || true
  docker_workflow:
    docker:
      - image: cimg/python:3.10.8
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          TAG=0.1.<< pipeline.number >>
          docker build -t $DOCKER_USERNAME/flask-polling-app:$TAG .
          docker login -u $DOCKER_USERNAME --password $DOCKER_PASSWORD
          docker push $DOCKER_USERNAME/flask-polling-app:$TAG
  snyk_container_test:
    docker:
    - image: snyk/snyk-cli:npm
    steps:
    - checkout
    - run:
        command: | 
          TAG=0.1.<< pipeline.number >>
          snyk auth $SNYK_TOKEN
          snyk container test jiajunngjj/flask-polling-app:$TAG --file=./Dockerfile || true
  trigger_argocd:
    docker:
      - image: cimg/base:2022.04
    steps:
      - run : |
          TAG=0.1.<< pipeline.number >>
          git clone https://github.com/jiajunngjj/argocd-flask.git
          cd argocd-flask
          sed -i 's/\(flask-polling-app\)\(.*\)/\1:'$TAG'/' k8s/polling-app.yaml
          git config user.email "ngjiajun13@gmail.com"
          git config user.name "jiajunngjj"
          git add k8s/polling-app.yaml
          git commit -m "update from circleci to trigger argocd"
          git push https://$GITHUB_PERSONAL_TOKEN@github.com/jiajunngjj/argocd-flask.git
workflows:
  flask-deployment-pipeline:
    jobs:
      - build
      - snyk_code_test:
          requires:
            - build
      - snyk_oss_test:
          requires:
            - build
      - docker_workflow:
          requires:
            - snyk_code_test
            - snyk_oss_test
      - snyk_container_test:
          requires:
            - docker_workflow
      - trigger_argocd:
          requires:
            - snyk_container_test

